apiVersion: v1
kind: Pod
metadata:
  name: mlperf-gpu-onnx-ssd-resnet34
spec:
  volumes:
    - name: task-pv-storage
      hostPath:
        path: "/mnt/mlperf"
  restartPolicy: Never
  containers:
    - name: mlperf-infer-imgclassify-gpu
      image: tzourhs/mlperf-infer-imgclassify-gpu:1.4
      env:
      - name: DATA_DIR
        value: "/tmp/mlperf/data/coco-1200"
      - name: MODEL_DIR
        value: "/tmp/mlperf/models/onnx_ssd_resnet_34"
      volumeMounts:
        - mountPath: "/tmp/mlperf"
          name: task-pv-storage
      workingDir: "/tmp/inference/vision/classification_and_detection/"
      command: ["/bin/bash", "-c", "./run_local.sh onnxruntime ssd-resnet34 gpu --accuracy"]
      resources:
        limits:
          nvidia.com/gpu: 1
