apiVersion: v1
kind: Pod
metadata:
  name: mlperfgpu
spec:
  volumes:
    - name: task-pv-storage
      hostPath:
        path: "/mnt/mlperf"
  restartPolicy: Never
  containers:
    - name: mlperf-infer-imgclassify-gpu
      image: tzourhs/mlperf-infer-imgclassify-gpu:1.2
      env:
      - name: DATA_DIR
        value: "/tmp/mlperf/data/imagenet2012"
      - name: MODEL_DIR
        value: "/tmp/mlperf/models/resnet50_tf"
      volumeMounts:
        - mountPath: "/tmp/mlperf"
          name: task-pv-storage
      workingDir: "/tmp/inference/vision/classification_and_detection/"
      command: ["/bin/bash", "-c", "./run_local.sh tf resnet50 gpu --accuracy"]
      resources:
        limits:
          nvidia.com/gpu: 1
