apiVersion: v1
kind: Pod
metadata:
  name: mlperf-gpu-{backend}-{model}
spec:
  volumes:
    - name: task-pv-storage
      hostPath:
        path: "/mnt/mlperf"
  restartPolicy: Never
  containers:
    - name: mlperf-infer-imgclassify-gpu
      image: tzourhs/mlperf-infer-imgclassify-gpu:1.4
      imagePullPolicy: IfNotPresent
      env:
      - name: DATA_DIR
        value: "/tmp/mlperf/data/{data}"
      - name: MODEL_DIR
        value: "/tmp/mlperf/models/{model}-{backend}"
      - name: EXTRA_OPS
        value: "--scenario {scenario} --time {time}"
      volumeMounts:
        - mountPath: "/tmp/mlperf"
          name: task-pv-storage
      workingDir: "/tmp/inference/vision/classification_and_detection/"
      command: ["/bin/bash", "-c", "./run_local.sh {backend} {model} gpu --accuracy"]
      resources:
        requests:
          ephemeral-storage: "7Gi"
        limits:
          nvidia.com/gpu: 1
